# Sales Records Analysis 
### Author: Angel Osorio 
### Exercise 2.E Using functions for analyzing data 
This notebook analyzes a small sales dataset using Python functions. 
Each function takes the full dataset as its first argument.  

In [15]:
sales_data = [
 ('Laptop', 'East', 1200.00),
 ('Phone', 'West', 850.00),
 ('Tablet', 'East', 400.00),
 ('Monitor', 'South', 650.00),
 ('Keyboard', 'West', 75.00),
 ('Laptop', 'South', 1150.00),
 ('Phone', 'East', 900.00),
 ('Tablet', 'West', 425.00),
 ('Monitor', 'East', 680.00),
 ('Keyboard', 'South', 80.00),
 ('Laptop', 'West', 1300.00),
 ('Phone', 'West', 820.00),
]

## Lab 1. Total sales by region 

In [16]:
def region_total(data, region):
    return sum(amt for _, r, amt in data if r == region)

In [17]:
print(region_total(sales_data, 'East'))
print(region_total(sales_data, 'West'))
print(region_total(sales_data, 'South'))

3180.0
3470.0
1880.0


## Lab 2. Count of sales by region 

In [18]:
def region_count(data, region):
    return sum(1 for _, r, _ in data if r == region)

In [19]:
print(region_count(sales_data, 'East')) 
print(region_count(sales_data, 'West')) 
print(region_count(sales_data, 'South')) 

4
5
3


## Lab 3. Average sale amount by region 

In [20]:
def region_average(data, region):
    count = region_count(data, region)
    return region_total(data, region) / count if count else 0

In [22]:
print(region_average(sales_data, 'East'))
print(region_average(sales_data, 'West'))
print(region_average(sales_data, 'South'))
print(region_average(sales_data, 'North'))  # Should handle division by zero gracefully

795.0
694.0
626.6666666666666
0


## Lab 4. Filter by sale amount 

In [23]:
def sales_above_threshold(data, threshold):
    return [record for record in data if record[2] > threshold]

In [24]:
for record in sales_above_threshold(sales_data, 500.00):
    print(record)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


## Lab 5. Top Sale and Bottom Sale

In [32]:
def top_sale(data):
    return max(data, key=lambda x: x[2])
def bottom_sale(data):
    return min(data, key=lambda x: x[2])

In [33]:
print(top_sale(sales_data))
print(bottom_sale(sales_data))

('Laptop', 'West', 1300.0)
('Keyboard', 'West', 75.0)


Results: The top sale was a laptop in the west region for $1300.00
The bottom sale was a keyboard in the west for $75.00

## Lab 6. Apply a discount

In [35]:
def apply_discount(data, discount_pct):
    return list(map(lambda s: (s[0], s[1], s[2] * (1 - discount_pct)), data))
print(apply_discount(sales_data, 0.15))

[('Laptop', 'East', 1020.0), ('Phone', 'West', 722.5), ('Tablet', 'East', 340.0), ('Monitor', 'South', 552.5), ('Keyboard', 'West', 63.75), ('Laptop', 'South', 977.5), ('Phone', 'East', 765.0), ('Tablet', 'West', 361.25), ('Monitor', 'East', 578.0), ('Keyboard', 'South', 68.0), ('Laptop', 'West', 1105.0), ('Phone', 'West', 697.0)]


## Lab 7. Unique Regions

In [36]:
def unique_regions(data):
    return sorted(set(r for _, r, _ in data))
print(unique_regions(sales_data))

['East', 'South', 'West']


## Lab 8. Region Summary

In [49]:
def filter_by_region(data, region):
    return [record for record in data if record[1] == region]
def region_summary(data, region):
    regional_data = filter_by_region(data, region)
    total = region_total(data, region)
    count = region_count(data, region)
    average = region_average(data, region)
    top = top_sale(regional_data)
    bot = bottom_sale(regional_data)

    print(f"=== {region} Region ===")
    print(f"Records: {count}")
    print(f"Total Sales: ${total:,.2f}")
    print(f"Average Sale: ${average:,.2f}")
    print(f"Top Sale: {top[0]} — ${top[2]:,.2f}")
    print(f"Bottom Sale: {bot[0]} — ${bot[2]:,.2f}")
    print()


## Lab 9. Full Summary

In [50]:
for region in unique_regions(sales_data):
    region_summary(sales_data, region)

=== East Region ===
Records: 4
Total Sales: $3,180.00
Average Sale: $795.00
Top Sale: Laptop — $1,200.00
Bottom Sale: Tablet — $400.00

=== South Region ===
Records: 3
Total Sales: $1,880.00
Average Sale: $626.67
Top Sale: Laptop — $1,150.00
Bottom Sale: Keyboard — $80.00

=== West Region ===
Records: 5
Total Sales: $3,470.00
Average Sale: $694.00
Top Sale: Laptop — $1,300.00
Bottom Sale: Keyboard — $75.00

